apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  dataDirHostPath: /var/lib/rook
  cephVersion:
    image: quay.io/ceph/ceph:v18
    allowUnsupported: true
  mon:
    count: 1
    allowMultiplePerNode: true
  mgr:
    count: 1
    allowMultiplePerNode: true
    modules:
      - name: rook
        enabled: true
  dashboard:
    enabled: true
  crashCollector:
    disable: true
  storage:
    useAllNodes: true
    useAllDevices: false
    config:
      storeType: "filestore"
      databaseSizeMB: "1024"
      journalSizeMB: "1024"
    volumeClaimTemplates:
      - metadata:
          name: osd1
        spec:
          resources:
            requests:
              storage: 1Gi
          storageClassName: ceph-block
          volumeMode: Filesystem
          accessModes: [ "ReadWriteOnce" ]
      - metadata:
          name: osd2
        spec:
          resources:
            requests:
              storage: 1Gi
          storageClassName: ceph-block
          volumeMode: Filesystem
          accessModes: [ "ReadWriteOnce" ]
      - metadata:
          name: osd3
        spec:
          resources:
            requests:
              storage: 1Gi
          storageClassName: ceph-block
          volumeMode: Filesystem
          accessModes: [ "ReadWriteOnce" ]
  monitoring:
    enabled: false
  healthCheck:
    daemonHealth:
      mon:
        interval: 45s
        timeout: 600s
  priorityClassNames:
    all: system-node-critical
    mgr: system-cluster-critical
  disruptionManagement:
    managePodBudgets: true
  cephConfig:
    global:
      osd_pool_default_size: "1"
      mon_warn_on_pool_no_redundancy: "false"
      bdev_flock_retry: "20"
      bluefs_buffered_io: "false"
      mon_data_avail_warn: "10"
