apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: just-test-pvc
  labels:
    app: just-test-app
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi