vpc_cidr_block             = "10.0.0.0/16"
private_subnet_cidr_blocks = ["10.0.1.0/24", "10.0.2.0/24", "10.0.3.0/24"]
public_subnet_cidr_block   = ["10.0.4.0/24", "10.0.5.0/24", "10.0.6.0/24"]
region                     = "us-east-1"
avail_zone                 = ["us-east-1a", "us-east-1b", "us-east-1c"]
#env_prefix = "env_prefix"
#instance-type = "t2.micro"
#my-ip = ["0.0.0.0/0"]
#private_key_location = "/Users/vasilijkazmin/.ssh/AWS-servers-key.pem"
#subnet_cidr_blocks = "10.0.4.0/24"
#ssh_key_private = "~/.ssh/AWS-servers-key.pem"
//fargate_private_subnet = [element(module.myapp-vpc.private_subnets, 0)]
//vpc_subnets = ["module.myapp-vpc.private_subnets", "module.myapp-vpc.public_subnets"]
//azs = ["us-east-1a", "us-east-1b", "us-east-1c"]