apiVersion: v1
kind: Pod
metadata:
  name: app-3
spec:
  containers:
    - name: app-3
      image: busybox
      command: ["/bin/sh", "-c"]
      args: ["tail -f /dev/null"]
      volumeDevices:
        - name: data
          devicePath: /dev/xvda
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: block-claim-3